[project]
name = "CloudStore"
version = "0.1.0"

[auth]
enabled = true
site_url = "http://localhost:3333"
additional_redirect_urls = ["http://localhost:3333/*"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_autoconfirm = true

[storage]
enabled = true
file_size_limit = "5MB"
mime_types = ["image/png", "image/jpeg", "image/webp"]

[db]
enabled = true

[api]
enabled = true
port = 54321
